version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: secusync-app:local
    ports:
      - "3001:3001"
    networks:
      - secusync-network
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  secusync-network:
    external: true
